vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /uploads/products/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true 
            delete_on_update: true
